arch:
  - amd64

language: go
go:
  - 1.15.x
env:
  - GO111MODULE=on
  global:
    - CODECOV_TOKEN='86e6fe78-f9a9-405d-babc-ecc289950f1a'
script:
  - go mod vendor
  - go get -u github.com/goware/modvendor
  - modvendor -copy="**/*.c **/*.h **/*.proto" -v
  - go test -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)