arch:
  - amd64

language: go
go:
  - 1.15.x
env:
  - CODECOV_TOKEN='86e6fe78-f9a9-405d-babc-ecc289950f1a'
  - GO111MODULE=on
before_install:
  - go get -u github.com/goware/modvendor
script:
  - go mod vendor
  - modvendor -copy="**/*.c **/*.h **/*.proto" -v
  - go test -coverprofile=coverage.txt ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)